
x=3
try:
    print(x)
except:
    print("An Exception Occured")
else:
    print("There Is no error")
finally:
    print("Always Excuted")

